# Generated by Django 5.2.4 on 2025-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutpage_title', models.CharField(max_length=500)),
                ('aboutpage_img', models.CharField(max_length=500)),
                ('aboutpage_desc', models.TextField()),
                ('aboutpage_uploading', models.FileField(default=None, max_length=500, null=True, upload_to='aboutpage')),
            ],
        ),
    ]
