# Generated by Django 5.2.4 on 2025-10-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=500)),
                ('service_img', models.CharField(max_length=500)),
                ('service_desc', models.TextField()),
                ('service_uploading', models.FileField(default=None, max_length=500, null=True, upload_to='Service')),
            ],
        ),
    ]
