# Generated by Django 5.2.4 on 2025-08-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=500)),
                ('Usersubject', models.CharField(max_length=500)),
                ('UserEmail', models.CharField(max_length=500)),
                ('Usermessage', models.TextField()),
            ],
        ),
    ]
