# Generated by Django 5.2.4 on 2025-09-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contctdetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='Submitdate',
            field=models.DateTimeField(null=True),
        ),
    ]
