# Generated by Django 5.2.4 on 2025-10-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contctdetail', '0002_contactform_submitdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='Submitdate',
        ),
    ]
