# Generated by Django 5.2.4 on 2025-10-24 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contctdetail', '0003_remove_contactform_submitdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='submitdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
