# Generated by Django 5.2.4 on 2025-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderupdation', '0002_alter_sliderupdate_slider_uploading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderupdate',
            name='slider_uploading',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='Sliderupdation'),
        ),
    ]
